spring:
  application:
    name: pcss-authdemo
server:
  port: ${port:8080}
  servlet:
    context-path: /authdemo
  # enables reverse proxy with x-forwarded-* headers
#  use-forward-headers: true
management:
  endpoints:
    web:
      exposure:
        include: '*'

security:
  oauth2:
    client:
      client-id: youroktaclientid
      client-secret: youroktaclientsecret
      access-token-uri: https://youroktadomain.oktapreview.com/oauth2/default/v1/token
      user-authorization-uri: https://youroktadomain.oktapreview.com/oauth2/default/v1/authorize
      scope: openid profile email
    resource:
      user-info-uri: https://youroktadomain.oktapreview.com/oauth2/default/v1/userinfo
      token-info-uri: https://youroktadomain.oktapreview.com/oauth2/default/v1/introspect
      prefer-token-info: false

logging:
  level:
    com.swissre.pcss.web: info  # set to debug if you want to see headers and body content
    org.hibernate: # set to trace to log sql statements and bindings
      type.descriptor.sql: info
      SQL: info
    org.springframework: info
    org.springframework.security: debug
    org.springframework.boot.autoconfigure.security: info
    org.springframework.web.client: debug

app:
  pingFederateKeyUrl: https://int-idp-dev.swissre.com:9031/ext/oauth/x509/kid
